version: '2'
services:
    jh20180807-app:
        image: jh20180807
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://jh20180807-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=jh20180807
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jh20180807-mongodb:
        extends:
            file: mongodb.yml
            service: jh20180807-mongodb
