version: '2'
services:
    jh20180807-mongodb:
        image: mongo:3.6.3
        ports:
            - "27017:27017"
        command: mongos --configdb jh20180807-mongodb-config
    jh20180807-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    jh20180807-mongodb-config:
        image: mongo:3.6.3
        container_name: jh20180807-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
